AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ontheroad-s3-sync

  Sample SAM Template for ontheroad-s3-sync

Globals:
  Function:
    Timeout: 3

Resources:
  OntheroadS3Sync:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../ontheroad-s3-sync/src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          MY_SQS_QUEUE_URL: !Ref s3SyncQueue
      Events:
        SqsJobQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt s3SyncQueue.Arn
            BatchSize: 1
  s3SyncQueue:
    Type: AWS::SQS::Queue
  OnTheRoadECR:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: ontheroad-api

Outputs:
  OntheroadS3Sync:
    Description: "OntheroadS3Sync Function ARN consumes messages from SQS and publishes image body to S3"
    Value: !GetAtt OntheroadS3Sync.Arn
  OntheroadS3SyncIamRole:
    Description: "Implicit IAM Role created for OntheroadS3Sync function"
    Value: !GetAtt OntheroadS3SyncRole.Arn
  s3SyncQueue:
    Value: !GetAtt s3SyncQueue.QueueName
