on:
  workflow_dispatch:
    inputs:
      regions:
        description: 'AWS Region'
        required: true
        default: 'eu-west-1'
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name
      # sam build
#      - run: sam build --use-container --template-file cloudformation/ontheroad-s3-sync-template.yaml

# Run Unit tests- Specify unit tests here

# sam deploy
#      - run: sam deploy --template-file cloudformation/infra-pipeline.yml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ontheroad-s3-sync --s3-bucket ontheroad-s3-sync --capabilities CAPABILITY_IAM --region eu-west-1
